apiVersion: v1
kind: ConfigMap
metadata:
  name: nfd-worker
#  namespace: openshift-nfd
data:
  nfd-worker-conf: |
    sources:
      pci:
        deviceLabelFields:
          - "vendor"
        deviceClassWhitelist:
          - "0200"
          - "03"
          - "12"
    
    #      - "class"
          
    #      - "device"
    #      - "subsystem_vendor"
    #      - "subsystem_device"
